# Generated by Django 4.0.5 on 2022-08-22 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_alter_story_options_story_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='approved_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='story',
            name='category',
            field=models.CharField(choices=[('Choose option', 'Choose option'), ('Politics', 'Politics'), ('Social', 'Social'), ('Sports', 'Sports'), ('Entertainment', 'Entertainment'), ('More', 'More')], default='Choose option', max_length=50),
        ),
        migrations.AddField(
            model_name='story',
            name='journalist_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='story',
            name='post_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='story',
            name='story',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='story',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
