# Generated by Django 4.0.5 on 2022-08-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_story_approved_date_story_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.CharField(choices=[('Choose option:', 'Choose option:'), ('Politics', 'Politics'), ('Social', 'Social'), ('Sports', 'Sports'), ('Entertainment', 'Entertainment'), ('More', 'More')], default='Choose option', max_length=50),
        ),
        migrations.AlterField(
            model_name='story',
            name='pic_1',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='story',
            name='pic_2',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='story',
            name='pic_3',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
